import type { Locale } from "./i18n";
const en = {
  themes: "Themes", light: "Light theme", dark: "Dark theme", preset: "Preset", custom: "Custom", accent: "Accent", background: "Background", foreground: "Text", contrast: "Surface contrast", preview: "Preview", sample: "Make space for your ideas.", task: "New task", fonts: "Typography", uiFont: "UI font", codeFont: "Code font", uiSize: "UI font size", codeSize: "Code font size", fontHelp: "Choose a font or enter an installed font name. Unavailable fonts fall back to the system font; no downloads.", behavior: "Interface", pointer: "Pointer cursor", pointerHelp: "Show a pointing hand over interactive controls.", translucent: "Translucent sidebar", translucentHelp: "Blend and blur the sidebar within the app window.", scope: "Custom colors and fonts apply to the desktop shell. The chat follows light/dark mode after restarting the app.", copy: "Copy theme", import: "Import theme", reset: "Reset theme", resetAll: "Reset all appearance", confirmReset: "Reset colors, fonts, sizes and interface options? Theme mode stays unchanged.", confirm: "Reset", cancel: "Cancel", apply: "Import", importHelp: "Paste DSH theme JSON. Its light/dark destination is included in the file. Codex theme strings are not supported.", copied: "Theme copied", imported: "Theme imported", invalid: "Invalid theme: use DSH theme v1, six-digit HEX colors and contrast 0–100.", saveError: "Could not save. Previous settings remain active.", copyError: "Clipboard unavailable. Select and copy the theme below.", invalidColor: "Use #RRGGBB.", resetDone: "Appearance reset", fontInvalid: "Enter a font name (up to 80 letters, numbers, spaces, dots, underscores or hyphens).", system: "System font", active: "Active", editing: "Independent preview", themeFormat: "DSH theme JSON", saved: "Saved automatically"
};
type Messages = Record<keyof typeof en, string>;
const zh: Messages = {
  themes: "主题", light: "浅色主题", dark: "深色主题", preset: "预设", custom: "自定义", accent: "强调色", background: "背景色", foreground: "文字颜色", contrast: "层次对比度", preview: "预览", sample: "为你的想法留出空间。", task: "新任务", fonts: "字体与字号", uiFont: "界面字体", codeFont: "代码字体", uiSize: "界面字号", codeSize: "代码字号", fontHelp: "选择字体或输入已安装的字体名称。字体不可用时自动回退，不会下载字体。", behavior: "界面交互", pointer: "手形光标", pointerHelp: "在可交互控件上显示手形光标。", translucent: "半透明侧栏", translucentHelp: "在应用窗口内部混合并模糊侧栏背景。", scope: "自定义颜色和字体作用于桌面外壳。聊天区的明暗模式在重启应用后同步。", copy: "复制主题", import: "导入主题", reset: "重置主题", resetAll: "重置全部外观", confirmReset: "重置颜色、字体、字号和界面选项？主题模式保持当前选择。", confirm: "重置", cancel: "取消", apply: "导入", importHelp: "粘贴 DSH 主题 JSON，文件会指定浅色或深色主题。暂不支持直接导入 Codex 主题字符串。", copied: "主题已复制", imported: "主题已导入", invalid: "主题无效：请使用 DSH theme v1、六位 HEX 颜色及 0–100 对比度。", saveError: "保存失败，已保留原设置。", copyError: "无法访问剪贴板，请选中下方主题内容复制。", invalidColor: "请输入 #RRGGBB。", resetDone: "外观已重置", fontInvalid: "字体名称限 80 字以内，可包含文字、数字、空格、点、下划线和连字符。", system: "系统字体", active: "使用中", editing: "独立预览", themeFormat: "DSH 主题 JSON", saved: "自动保存"
};
const hant: Messages = { themes:"主題",light:"淺色主題",dark:"深色主題",preset:"預設",custom:"自訂",accent:"強調色",background:"背景色",foreground:"文字顏色",contrast:"層次對比度",preview:"預覽",sample:"為你的想法留出空間。",task:"新任務",fonts:"字型與字級",uiFont:"介面字型",codeFont:"程式碼字型",uiSize:"介面字級",codeSize:"程式碼字級",fontHelp:"選擇字型或輸入已安裝的字型名稱。無法使用時自動回退，不會下載字型。",behavior:"介面互動",pointer:"手形游標",pointerHelp:"在可互動控制項上顯示手形游標。",translucent:"半透明側欄",translucentHelp:"在應用程式視窗內混合並模糊側欄背景。",scope:"自訂色彩和字型套用於桌面外殼。聊天區的明暗模式在重新啟動後同步。",copy:"複製主題",import:"匯入主題",reset:"重設主題",resetAll:"重設所有外觀",confirmReset:"重設色彩、字型、字級和介面選項？主題模式維持目前選擇。",confirm:"重設",cancel:"取消",apply:"匯入",importHelp:"貼上 DSH 主題 JSON，檔案會指定淺色或深色主題。不支援 Codex 主題字串。",copied:"已複製主題",imported:"已匯入主題",invalid:"主題無效：請使用 DSH theme v1、六位 HEX 色彩和 0–100 對比度。",saveError:"儲存失敗，已保留原設定。",copyError:"無法存取剪貼簿，請選取下方內容複製。",invalidColor:"請輸入 #RRGGBB。",resetDone:"已重設外觀",fontInvalid:"字型名稱限 80 字，可含文字、數字、空格、點、底線和連字號。",system:"系統字型",active:"使用中",editing:"獨立預覽",themeFormat:"DSH 主題 JSON",saved:"自動儲存" };
const ja: Messages = { themes:"テーマ",light:"ライトテーマ",dark:"ダークテーマ",preset:"プリセット",custom:"カスタム",accent:"アクセント",background:"背景",foreground:"文字色",contrast:"面のコントラスト",preview:"プレビュー",sample:"アイデアのための空間。",task:"新しいタスク",fonts:"フォントとサイズ",uiFont:"UI フォント",codeFont:"コードフォント",uiSize:"UI 文字サイズ",codeSize:"コード文字サイズ",fontHelp:"フォントを選択するか、インストール済みの名前を入力します。利用できない場合は標準フォントを使用します。ダウンロードは行いません。",behavior:"操作",pointer:"ポインターカーソル",pointerHelp:"操作可能な項目に手の形のカーソルを表示します。",translucent:"半透明サイドバー",translucentHelp:"アプリ内のサイドバー背景を混合してぼかします。",scope:"カスタム色とフォントはデスクトップ部分に適用されます。チャットの明暗モードはアプリ再起動後に同期されます。",copy:"テーマをコピー",import:"テーマを読み込む",reset:"テーマをリセット",resetAll:"外観をすべてリセット",confirmReset:"色、フォント、サイズ、操作設定をリセットしますか？表示モードは維持されます。",confirm:"リセット",cancel:"キャンセル",apply:"読み込む",importHelp:"DSH テーマ JSON を貼り付けてください。明暗の適用先はファイルに含まれます。Codex テーマ文字列には対応していません。",copied:"コピーしました",imported:"読み込みました",invalid:"無効なテーマです。DSH theme v1、6 桁の HEX 色、0–100 のコントラストを使用してください。",saveError:"保存できませんでした。以前の設定を維持しています。",copyError:"クリップボードを利用できません。下の内容を選択してコピーしてください。",invalidColor:"#RRGGBB を入力してください。",resetDone:"外観をリセットしました",fontInvalid:"フォント名は 80 文字以内で、文字、数字、空白、ピリオド、下線、ハイフンを使用してください。",system:"システムフォント",active:"使用中",editing:"独立プレビュー",themeFormat:"DSH テーマ JSON",saved:"自動保存" };
const ko: Messages = { themes:"테마",light:"밝은 테마",dark:"어두운 테마",preset:"프리셋",custom:"사용자 지정",accent:"강조색",background:"배경색",foreground:"글자색",contrast:"표면 대비",preview:"미리 보기",sample:"아이디어를 위한 공간.",task:"새 작업",fonts:"글꼴과 크기",uiFont:"인터페이스 글꼴",codeFont:"코드 글꼴",uiSize:"인터페이스 글자 크기",codeSize:"코드 글자 크기",fontHelp:"글꼴을 선택하거나 설치된 글꼴 이름을 입력하세요. 사용할 수 없으면 기본 글꼴로 표시하며 다운로드하지 않습니다.",behavior:"인터페이스",pointer:"손 모양 커서",pointerHelp:"조작 가능한 항목 위에 손 모양 커서를 표시합니다.",translucent:"반투명 사이드바",translucentHelp:"앱 창 내부에서 사이드바 배경을 혼합하고 흐리게 표시합니다.",scope:"사용자 지정 색상과 글꼴은 데스크톱 셸에 적용됩니다. 채팅의 밝기 모드는 앱을 다시 시작하면 동기화됩니다.",copy:"테마 복사",import:"테마 가져오기",reset:"테마 초기화",resetAll:"모든 외관 초기화",confirmReset:"색상, 글꼴, 크기와 인터페이스 설정을 초기화할까요? 테마 모드는 유지됩니다.",confirm:"초기화",cancel:"취소",apply:"가져오기",importHelp:"DSH 테마 JSON을 붙여 넣으세요. 파일에 밝은/어두운 대상이 지정됩니다. Codex 테마 문자열은 지원하지 않습니다.",copied:"테마 복사됨",imported:"테마 가져옴",invalid:"잘못된 테마입니다. DSH theme v1, 6자리 HEX 색상, 0–100 대비를 사용하세요.",saveError:"저장하지 못했습니다. 이전 설정을 유지합니다.",copyError:"클립보드를 사용할 수 없습니다. 아래 내용을 선택해서 복사하세요.",invalidColor:"#RRGGBB를 입력하세요.",resetDone:"외관 초기화됨",fontInvalid:"글꼴 이름은 80자 이하이며 문자, 숫자, 공백, 마침표, 밑줄, 하이픈만 사용할 수 있습니다.",system:"시스템 글꼴",active:"사용 중",editing:"독립 미리 보기",themeFormat:"DSH 테마 JSON",saved:"자동 저장" };
const ru: Messages = { themes:"Темы",light:"Светлая тема",dark:"Тёмная тема",preset:"Набор",custom:"Своя тема",accent:"Акцент",background:"Фон",foreground:"Текст",contrast:"Контраст поверхностей",preview:"Предпросмотр",sample:"Пространство для ваших идей.",task:"Новая задача",fonts:"Шрифты и размеры",uiFont:"Шрифт интерфейса",codeFont:"Шрифт кода",uiSize:"Размер текста интерфейса",codeSize:"Размер текста кода",fontHelp:"Выберите шрифт или введите имя установленного. Если его нет, используется системный шрифт. Загрузка не требуется.",behavior:"Интерфейс",pointer:"Курсор-указатель",pointerHelp:"Показывать курсор в виде руки над интерактивными элементами.",translucent:"Полупрозрачная боковая панель",translucentHelp:"Смешивать и размывать фон панели внутри окна приложения.",scope:"Свои цвета и шрифты применяются к оболочке. Светлый/тёмный режим чата синхронизируется после перезапуска приложения.",copy:"Копировать тему",import:"Импорт темы",reset:"Сбросить тему",resetAll:"Сбросить оформление",confirmReset:"Сбросить цвета, шрифты, размеры и параметры интерфейса? Режим темы сохранится.",confirm:"Сбросить",cancel:"Отмена",apply:"Импорт",importHelp:"Вставьте JSON темы DSH. Целевой режим указан в файле. Строки тем Codex не поддерживаются.",copied:"Тема скопирована",imported:"Тема импортирована",invalid:"Неверная тема: нужны DSH theme v1, шестизначные HEX-цвета и контраст 0–100.",saveError:"Не удалось сохранить. Предыдущие настройки сохранены.",copyError:"Буфер обмена недоступен. Выделите и скопируйте текст ниже.",invalidColor:"Введите #RRGGBB.",resetDone:"Оформление сброшено",fontInvalid:"Имя шрифта: до 80 букв, цифр, пробелов, точек, подчёркиваний или дефисов.",system:"Системный шрифт",active:"Активна",editing:"Отдельный просмотр",themeFormat:"JSON темы DSH",saved:"Автосохранение" };
export const appearanceText = (locale: Locale): Messages => ({ en, zh, "zh-Hant": hant, ja, ko, ru })[locale];

const presetNames = {
  zh: ["DSH", "海洋", "森林", "紫罗兰", "琥珀", "玫瑰"],
  "zh-Hant": ["DSH", "海洋", "森林", "紫羅蘭", "琥珀", "玫瑰"],
  en: ["DSH", "Ocean", "Forest", "Violet", "Amber", "Rose"],
  ja: ["DSH", "海", "森", "すみれ", "琥珀", "ローズ"],
  ko: ["DSH", "바다", "숲", "바이올렛", "앰버", "로즈"],
  ru: ["DSH", "Океан", "Лес", "Фиалка", "Янтарь", "Роза"],
};
export const presetLabel = (locale: Locale, index: number): string => presetNames[locale][index];

const frameNames = {
  zh: { frame: "边框色", surface: "前景色" },
  "zh-Hant": { frame: "邊框色", surface: "前景色" },
  en: { frame: "Frame color", surface: "Surface color" },
  ja: { frame: "フレーム色", surface: "前景の面色" },
  ko: { frame: "프레임 색상", surface: "패널 색상" },
  ru: { frame: "Цвет рамки", surface: "Цвет панелей" },
};
export const frameText = (locale: Locale) => frameNames[locale];

const pasteMessages = {
 zh: { paste: "粘贴主题", pasted: "主题已粘贴", failed: "无法读取剪贴板，请使用下方的导入主题粘贴。" },
 "zh-Hant": { paste: "貼上主題", pasted: "已貼上主題", failed: "無法讀取剪貼簿，請使用下方的匯入主題貼上。" },
 en: { paste: "Paste theme", pasted: "Theme pasted", failed: "Cannot read the clipboard. Use Import theme below to paste manually." },
 ja: { paste: "テーマを貼り付け", pasted: "テーマを貼り付けました", failed: "クリップボードを読めません。下のテーマ読み込みから貼り付けてください。" },
 ko: { paste: "테마 붙여넣기", pasted: "테마를 붙여넣었습니다", failed: "클립보드를 읽을 수 없습니다. 아래 테마 가져오기를 사용하세요." },
 ru: { paste: "Вставить тему", pasted: "Тема вставлена", failed: "Не удалось прочитать буфер обмена. Используйте импорт темы ниже." },
};
export const pasteText = (locale: Locale) => pasteMessages[locale];
